receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  # Local scrape endpoint for debugging
  prometheus:
    endpoint: "0.0.0.0:8889"

  # Correct exporter for Mimir
  prometheusremotewrite/mimir:
    endpoint: "http://load-balancer:9009/api/v1/push"
    headers:
      X-Scope-OrgID: demo

service:
  pipelines:
    metrics/otlp:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite/mimir, prometheus]
