# config/otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889" # optional scrape endpoint
  otlp/mimir:
    endpoint: "http://load-balancer:9009" # your Mimir load balancer
    headers:
      "X-Scope-OrgID": "demo"

processors:
  batch:

service:
  pipelines:
    metrics/otlp:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/mimir, prometheus]
