receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889" # optional scrape endpoint for debugging
  prometheusremotewrite/mimir:
    endpoint: "http://load-balancer:9009/api/v1/push"
    headers:
      X-Scope-OrgID: demo

processors:
  batch:

service:
  pipelines:
    metrics/otlp:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite/mimir, prometheus]
