version: '3'

services:
  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:1.34
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775"   # Zipkin Thrift
      - "6831:6831/udp" # Jaeger agent
      - "6832:6832/udp" # Jaeger agent
      - "5778:5778"     # Jaeger UI
      - "16686:16686"   # Jaeger UI
      - "14268:14268"   # Jaeger collector HTTP
      - "14250:14250"   # Jaeger gRPC
      - "14255:14255"   # Jaeger query HTTP

  # Service 1 
  service1:
    build: ./SA
    container_name: service1
    depends_on:
      - service2
      - jaeger
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=5775
    ports:
      - "5001:5000"

  # Service 2 
  service2:
    build: ./SB
    container_name: service2
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=5775
    ports:
      - "5002:5001"

