auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  wal:
    enabled: true
    dir: /loki/wal   # changed

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index   # changed
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks   # changed

compactor:
  working_directory: /loki/compactor   # 👈 this is required
  shared_store: filesystem

limits_config:
  enforce_metric_name: false
